apiVersion: v1
kind: PersistentVolume # Create PV 
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: {{ .Values.labels.app }}
spec:
  storageClassName: {{ .Values.pv.storageClassName }}
  capacity:
    storage: {{ .Values.pv.storageCapacity }} # Sets PV's size
  accessModes:
    - {{ .Values.pv.accessModes }}
  hostPath:
    path: {{ .Values.pv.hostPath }} #Sets PV's host path