apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-claim # Sets PVC's name
  labels:
    app: {{ .Values.labels.app }} # Defines app to create PVC for
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageResources }} # Sets PVC's size