apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp-k8s-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL
          envFrom:
            - configMapRef:
                name: postgres-secret # Using the ConfigMap postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "256m"
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim