apiVersion: v1
kind: Service # Create service
metadata:
  name: quizapp-api # Sets the service name
  labels:
    app: quizapp-api # Defines app to create service for
spec:
  type: ClusterPort # Sets the service type
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: quizapp-api