apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deploy
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: {{ .Values.deploy.image }}
          imagePullPolicy: {{ .Values.deploy.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config # Using the ConfigMap
          resources:
            requests:
              memory: "20Mi"
              cpu: "20m"
            limits:
              memory: "1Gi"
              cpu: "1000m"